Computer-Research-Association/cra-web-frontend

src/main.tsx

[JY] feat#1: testing

---

src/main.tsx

[CH] feat[#8]: 테스트용입니다.

---

package-lock.json
package.json
src/App.tsx
src/components/Board/Academic/AcademicDetail.tsx
src/components/Board/Academic/AcademicEdit.tsx
src/components/Board/Academic/AcademicList.tsx
src/components/Board/Academic/AcademicWrite.tsx
src/components/Board/Book/BookDetail.tsx
src/components/Board/Book/BookEdit.tsx
src/components/Board/Book/BookList.tsx
src/components/Board/Book/BookWrite.tsx
src/components/Board/Equipment/EquipmentDetail.tsx
src/components/Board/Equipment/EquipmentEdit.tsx
src/components/Board/Equipment/EquipmentList.tsx
src/components/Board/Equipment/EquipmentWrite.tsx
src/components/Board/Havruta/HavrutaDetail.tsx
src/components/Board/Havruta/HavrutaEdit.tsx
src/components/Board/Havruta/HavrutaList.tsx
src/components/Board/Havruta/HavrutaWrite.tsx
src/components/Board/Notice/NoticeDetail.tsx
src/components/Board/Notice/NoticeEdit.tsx
src/components/Board/Notice/NoticeList.tsx
src/components/Board/Notice/NoticeWrite.tsx
src/components/Intro/Intro.tsx
src/components/Login/Login.tsx
src/components/Main/Main.tsx
src/components/Recruit/Recruit.tsx
src/components/Register/Register.tsx
src/components/Router.tsx
src/main.tsx

intro, recruit, login, main, register, academic, book, equipment, havruta, notice와 관련된 Router 생성,
academic, book, equipment, havruta, notice는 게시판 기능을 하므로 Board 폴더 안에 정리
academic, book, equipment, havruta, notice는 Edit,Detail,List,Write 각각의 기능별로 분리

[JY] feat[#10]: Frontend Routing 설정

---

src/pages/Intro/IntroPage.css
src/pages/Intro/IntroPage.tsx
src/pages/Recruit/RecruitPage.css
src/pages/Recruit/RecruitPage.tsx

[SY] feat[#28]:소개,리크루팅 수정

---

src/components/Header/HeaderIntro.css
src/components/Header/HeaderIntro.tsx

[SY] feat[#28]: 인트로 헤더 추가

---

src/api/board.tsx
src/api/queryKey.tsx
src/components/Board/Detail/BoardDetail.tsx
src/components/Board/Edit/BoardEdit.module.css
src/components/Board/Edit/BoardEdit.tsx
src/components/Board/Item/BoardDetailItem.tsx
src/components/Board/Item/BoardItem.tsx
src/constants/category_strings_en.tsx
src/pages/Router.tsx

Detail 및 Update 페이지 추가 및 API 연결

feat[#38]: Board CRUD: Detail & Update 기능 구현

---

src/pages/Login/LoginPage.module.css
src/pages/Login/LoginPage.tsx

[KB] feat[#48]: 로그인 페이지 기본 UI 제작

---

src/pages/Login/LoginPage.tsx
src/pages/Main/MainPage.module.css
src/pages/Register/RegisterPage.module.css
src/pages/Register/RegisterPage.tsx

Feat/#64: 회원가입 페이지 생성

---

src/pages/AppRoutes.tsx
src/pages/Login/LoginPage.tsx
src/pages/Login/Search/ID/IDSearchPage.module.css
src/pages/Login/Search/ID/IDSearchPage.tsx
src/pages/Login/Search/PW/PWSearchPage.module.css
src/pages/Login/Search/PW/PWSearchPage.tsx

[KB] feat[#65]: ID/PW 찾기 페이지 CSS 및 라우팅, 하이퍼링크 설정

[KB] feat[#65]: ID/PW 찾기 페이지 CSS 및 라우팅, 하이퍼링크 설정

---

src/pages/Recruit/RecruitPage.module.css
src/pages/Recruit/RecruitPage.tsx

[SY] feat[#49]: 리크루팅 페이지 디자인 완료

---

src/store/authStore.tsx

기존 Local Stoarge 구현 방법에서 브라우저를 끄고 3일 뒤에 봤는데 로그인 토큰이 남아있어서 로그인이 유지되어있는 허점 발견으로 Session Storage로 구현 변경

로그인 관련 기능 Session Storage로 구현 변경

---

src/api/havruta/havruta.tsx
src/components/Havruta/HavrutaBoard/List/HavrutaBoardList.tsx

- 하브루타 게시판에서 하브루타 과목 불러올 때 admin api를 사용하던 거 권한 없는 누구나 불러올수 있도록 그냥 api 사용
- 권한 설정된 apiClient 설정
- Console창에 500, 404 에러 뜨던거 수정

하브루타 게시판 & 페이지네이션 관련 짜잘한 오류 수정

---

src/api/havruta/havruta.tsx
src/components/Havruta/HavrutaBoard/List/HavrutaBoardContainer.tsx
src/components/Havruta/HavrutaBoard/List/HavrutaBoardList.module.css
src/components/Havruta/HavrutaBoard/List/HavrutaBoardList.tsx
src/components/Havruta/HavrutaBoard/List/Sidebar/HavrutaSidebar.module.css
src/components/Havruta/HavrutaBoard/List/Sidebar/HavrutaSidebar.tsx
src/components/Pagination/Pagination.module.css
src/components/Pagination/Pagination.tsx
src/pages/Board/Havruta/HavrutaBoard/HavrutaBoardPage.tsx

- 하브루타 게시판 로직 관련 컴포넌트
- 하브루타 게시판 UI 관련 컴포넌트
- 하브루타 과목 사이드바 컴포넌트
- **페이지네이션 컴포넌트** (다른 게시판에도 사용할수 있게 분리해놈)

하브루타 게시판 페이지 컴포넌트 분리

---

src/api/board.tsx
src/api/queryKey.tsx
src/components/Board/BoardContainer.tsx
src/components/Board/List/BoardList.module.css
src/components/Board/List/BoardList.tsx
src/components/Pagination/Pagination.tsx
src/pages/Board/Academic/AcademicPage.tsx
src/pages/Board/Notice/NoticePage.tsx
src/styles/colors.css

> 하브루타 게시판과 거의 동일
- 페이지네이션 적용된 리스트 가져오는 API 불러오기
- 게시판 로직, UI 컴포넌트 분리
- 게시판에 페이지네이션 적용 (한 페이지에 게시물 10개)
- 게시물이 하나도 없을 때 페이지네이션 바 아예 안뜨게 설정
- 게시물이 하나도 없을 때 게시판에 게시물이 없다고 알려주는 문구 나오게 설정

공지, 학술 게시판에 페이지네이션 적용

---

src/components/Admin/AdminHome.tsx
src/components/Admin/AdminSideBar.tsx
src/components/Footer/Footer.module.css
src/components/Footer/Footer.tsx
src/pages/Admin/AdminPage.tsx
src/routes/adminHavrutaRoutes.ts

어드민 페이지 제작

---

src/pages/Intro/IntroPage.module.css
src/pages/Recruit/RecruitPage.module.css

- 헤더 사라짐 해결
- 좌우 여백 사라짐 해결
- 리크루팅 버튼 애니메이션 효과 추가

리크루팅 페이지 디자인 깨짐 현상 해결

---

src/components/Book/Edit/BookAdminEdit.tsx
src/components/Havruta/Havruta/Edit/HavrutaEdit.tsx
src/components/Item/Edit/ItemAdminEdit.tsx
src/components/Project/Edit/ProjectAdminEdit.tsx
src/pages/Intro/IntroPage.module.css
src/pages/Recruit/RecruitPage.module.css

`queryKey: QUERY_KEY.project.projectById(projectId)`
이런식으로 안된 것들 모두 수정

Query Key 사용 방법 수정

---

src/api/board.ts
src/api/comment.ts
src/api/havruta/havruta.ts
src/api/havruta/havrutaBoard.ts
src/api/item.ts
src/api/project.ts
src/components/Board/Detail/BoardDetail.tsx
src/components/Havruta/HavrutaBoard/Detail/HavrutaBoardDetail.tsx
src/components/Header/Main-Header/HeaderMain.module.css
src/pages/Error/ForbiddenPage.tsx
src/pages/Error/NotFoundPage.tsx
src/pages/Error/ServerErrorPage.tsx
src/routeTree.gen.ts
src/routes/errorRoute.ts
src/routes/notFoundRoute.ts
src/routes/routes.ts

- 404 이외에 403, 500 에러 페이지 제작
- Axios Status 불러와서 각각 페이지로 리다이렉팅
- 라우팅 수정
- 디자인 약간 수정

접근 할 수 업는 게시물 접근 시 예외처리 페이지

---

src/pages/Intro/IntroPage.module.css

인트로 페이지 모바일에서 문구 내려감 해결

---

src/api/board.ts
src/components/Board/List/BoardList.tsx

- 게시물 아래 줄 생기는거 해결
- 게시물 페이지 정렬 순서 오류 수정

게시물 페이지 정렬 순서 오류 수정

---

src/api/auth/authApi.ts
src/api/auth/authClient.ts
src/components/Header/Main-Header/HeaderMain.tsx
src/components/Modal/User/UserModal.tsx
src/store/authStore.ts

로그아웃 로직 구현
로그아웃하면 refreshToken 지워지는 로직 사용해서
로그아웃 하고 로그인 바로 되게 구현

로그아웃 로직 구현

---

src/api/board.ts
src/models/Board.ts
src/models/Havruta.ts

보드 인터페이스 수정

---

src/components/Auth/Login/LoginForm.tsx
src/components/Auth/Register/RegisterForm.tsx
src/pages/Register/RegisterCompletePage.tsx
src/routes/registerRoutes.ts
src/store/registerStore.ts
src/store/userStore.ts

회원 가입 후 리다이렉팅 하는 회원가입 환영 페이지에 이름, 아이디를 출력해 가독성을 높힘

회원 가입 환영 페이지 수정

---

src/components/Auth/Login/LoginForm.module.css
src/components/Auth/Login/LoginForm.tsx
src/components/Board/List/BoardList.module.css
src/components/Footer/Footer.module.css
src/components/Footer/Footer.tsx
src/components/Header/Main-Header/HeaderMain.module.css
src/components/Header/Main-Header/HeaderMain.tsx
src/components/Modal/User/MyUser/UserModal.module.css

반응형 디자인 조금

---

src/components/Board/Edit/BoardEdit.tsx
src/components/Board/Write/BoardWrite.tsx
src/components/Footer/Footer.tsx
src/components/Havruta/HavrutaBoard/Edit/HavrutaBoardEdit.tsx
src/components/Havruta/HavrutaBoard/Write/HavrutaBoardWrite.tsx
src/utils/dateForm.ts

현재 시간이 9시간 늦음 이슈가 생겨서 그냥 hours 변수에 9 더함
+ ESLint 빌드 오류 중 마크다운 깨짐 오류 해결

현재 시간이 9시간 늦음 이슈

---

src/components/Intro/Top/IntroTop.module.css

배포 용 페이지 설정

---

src/components/Board/Detail/BoardDetail.module.css
src/components/Board/Detail/BoardDetailItem.module.css
src/components/Board/Edit/BoardEdit.module.css
src/components/Board/Item/BoardItem.module.css
src/components/Board/Item/BoardItem.tsx
src/components/Board/List/BoardList.module.css
src/components/Board/List/BoardList.tsx
src/components/Board/Write/BoardWrite.module.css
src/components/Comment/Item/CommentItem.module.css
src/components/Comment/Write/CommentWrite.module.css
src/components/Havruta/HavrutaBoard/Detail/HavrutaBoardDetail.module.css
src/components/Havruta/HavrutaBoard/Detail/Item/HavrutaBoardDetailIItem.tsx
src/components/Havruta/HavrutaBoard/Detail/Item/HavrutaBoardDetailItem.module.css
src/components/Havruta/HavrutaBoard/Edit/HavrutaBoardEdit.module.css
src/components/Havruta/HavrutaBoard/Item/HavrutaBoardItem.module.css
src/components/Havruta/HavrutaBoard/Item/HavrutaBoardItem.tsx
src/components/Havruta/HavrutaBoard/List/Dropdown/HavrutaDropdown.module.css
src/components/Havruta/HavrutaBoard/List/Dropdown/HavrutaDropdown.tsx
src/components/Havruta/HavrutaBoard/List/HavrutaBoardList.module.css
src/components/Havruta/HavrutaBoard/List/HavrutaBoardList.tsx
src/components/Havruta/HavrutaBoard/List/Sidebar/HavrutaSidebar.module.css
src/components/Havruta/HavrutaBoard/Write/HavrutaBoardWrite.module.css
src/components/Header/Main-Header/HeaderMain.tsx
src/components/Pagination/Pagination.module.css
src/routes/routes.ts

하브루타 게시판 
공지, 학술 게시판
댓글
페이지네이션
등등

하브루타 게시판 반응형 디자인

---

src/pages/Recruit/RecruitPage.tsx

리크루팅 폼 링크 변경

---

src/components/Footer/Footer.tsx

인트로, 리크루팅 페이지에서 Footer 로고 안눌리게 예외 처리
